### ISSUE TITLE
Explanation of what it is this script does

### ISSUE THREAD

**Issue by siddharthist** [marshyski/quick-secure#6]
I can read bash, but it might be nice to provide a little explanation for how this script works? What is the industry baseline, and how does this script get you there? Whose standards are these? Why does this work?

**Comment by marshyski** [comment]
@siddharthist I'll work on!

**Comment by siddharthist** [comment]
Was this fixed?

**Comment by marshyski** [comment]
@siddharthist if you feel like it needs to be more verbose or richer comments, submit a PR.
https://github.com/marshyski/quick-secure/commit/dc59d2683e27e097c2bda239e02ce8555df82a1d
