### ISSUE TITLE
Cannot unlock screen, password works switching user or logging in after boot.

### ISSUE THREAD

**Issue by aitoehigie** [marshyski/quick-secure#7]
I use i3wm and noticed that since I installed this program, whenever I lock my system and try to login again it tells me my password is wrong so I have no choice but to completely reboot my system which is rather odd. How do I remove this from my system?

Thank you

**Comment by marshyski** [comment]
Hi @aitoehigie which OS, version and window manager/GUI are you using?  Removing it is easy, but reverting the changes are hard.  When you provide the information I can replicate it and tell you which permission you'll need to revert back.

**Comment by aitoehigie** [comment]
Hello,
I use Linux mint 19 with i3 windows manager and i3lock. Hope that's enough
information. I am suspecting that it changes my password whenever I lock my
system

Kind regards

**Comment by marshyski** [comment]
Hi @aitoehigie I found the fix for you. Please run the following commands as root in your terminal.

```
chown root:shadow {/etc/shadow,/etc/shadow-,/etc/gshadow,/etc/gshadow-}

chmod 0640 {/etc/shadow,/etc/shadow-,/etc/gshadow,/etc/gshadow-}
```

**Comment by aitoehigie** [comment]
Issue resolved.
Thanks
